### ISSUE TITLE
Produces an invalid json

### ISSUE THREAD

**Issue by yurivict** [hyperboria/python-cjdns#10]
Output produced by python-cjdns fails validation by jq. It deviates from the standard in two ways:
- it uses single quotes instead of the double-quotes
- 'u' isn't a valid symbol to label the unicode strings. Uncode characters use "\u", for example \u00f8C. No need to prefix every string.

**Comment by kyrias** [comment]
What output?

**Comment by yurivict** [comment]
This command:

```
import cjdns

cjdns = cjdns.connect('127.0.0.1', 11234, '')
peerStats = cjdns.InterfaceController_peerStats()
print peerStats
```

prints

```
{u'deprecation': u'public ...
```

**Comment by thefinn93** [comment]
Yep, that's how python renders dictionaries. if you want it as real JSON, do `print(json.dumps(peerStats))`
