### ISSUE TITLE
Please declare dependencies in setup.py

### ISSUE THREAD

**Issue by yurivict** [hyperboria/python-cjdns#9]
For example, it depends on "prettytable", "bencode", and they aren't in setup.py

**Comment by kyrias** [comment]
Technically the utils are secondary, since this is an API library.  I wonder if we should split utils into a separate package.

**Comment by yurivict** [comment]
Splitting too much maybe isn't a good idea. Too many small packages.

**Comment by yurivict** [comment]
You forgot the bencode dependency.

**Comment by kyrias** [comment]
The bencode library needed is part of the package itself.

**Comment by kyrias** [comment]
(cjdns doesn't actually use the standard bencode, it uses a modified version.)
